In [1]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
iris= load_iris()
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
df =pd.DataFrame(iris.data,columns = iris.feature_names)

In [6]:
df['flower']=iris.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
df['flower']= df['flower'].apply(lambda x: iris.target_names[x])

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.33, random_state=42)

In [12]:
from sklearn.svm import SVC

In [13]:
model = SVC(kernel = 'rbf' , C = 30 , gamma ='auto')

In [14]:
model.fit(X_train ,y_train)

SVC(C=30, gamma='auto')

In [15]:
model.score(X_test,y_test)

0.98

In [16]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(SVC(kernel = 'linear',C=10,gamma='auto') , iris.data , iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [27]:
cross_val_score(SVC(kernel = 'rbf',C=10,gamma='auto') , iris.data , iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [28]:
cross_val_score(SVC(kernel = 'rbf',C=20,gamma='auto') , iris.data , iris.target,cv=5,)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [29]:
import numpy as np

In [31]:
kernels= ['rbf','linear']
c=[1,10,20]
avg_scores ={}
for i in kernels:
    for j in c:
        cv_scores = cross_val_score(SVC(kernel = i,C=j,gamma='auto') , iris.data , iris.target,cv=5,)
        avg_scores[i + '_' + str(j)] = np.average(cv_scores)

In [32]:
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [33]:
from sklearn.model_selection import GridSearchCV

In [34]:
clf = GridSearchCV(SVC(gamma='auto'),{
    'C' :[1,10,20],'kernel':['rbf','linear']},cv=5,return_train_score =False)


In [36]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [37]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_

In [38]:
clf.cv_results_

{'mean_fit_time': array([0.00119667, 0.0004046 , 0.00099931, 0.00059829, 0.0009974 ,
        0.00079546]),
 'std_fit_time': array([3.98612518e-04, 4.95625698e-04, 1.01820087e-05, 4.88499796e-04,
        1.51240840e-06, 3.97748181e-04]),
 'mean_score_time': array([0.00059829, 0.00039878, 0.        , 0.00039868, 0.00059881,
        0.00060039]),
 'std_score_time': array([0.0004885 , 0.0004884 , 0.        , 0.00048829, 0.00048893,
        0.00049025]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [39]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001197      0.000399         0.000598        0.000488       1   
1       0.000405      0.000496         0.000399        0.000488       1   
2       0.000999      0.000010         0.000000        0.000000      10   
3       0.000598      0.000488         0.000399        0.000488      10   
4       0.000997      0.000002         0.000599        0.000489      20   
5       0.000795      0.000398         0.000600        0.000490      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [40]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [41]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [42]:
clf.best_score_

0.9800000000000001

In [43]:
from sklearn.model_selection import RandomizedSearchCV

In [53]:
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C' :[1,10,20],'kernel':['rbf','linear']},cv=5,return_train_score =False , n_iter =5)

In [54]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [55]:
df = pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
df

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1       1          rbf         0.980000
2      10          rbf         0.980000
3       1       linear         0.980000
4      10       linear         0.973333

In [56]:
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C' :[1,10,20],'kernel':['rbf','linear']},cv=5,return_train_score =False , n_iter =3)
rs.fit(iris.data,iris.target)
df = pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
df

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1      20          rbf         0.966667
2      20       linear         0.966667