In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits

In [4]:
digits = load_digits()

In [6]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=42)

In [7]:
X_train.shape

(1203, 64)

In [8]:
X_test.shape

(594, 64)

In [9]:
lr =LogisticRegression(max_iter=7400)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9730639730639731

In [10]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9865319865319865

In [14]:
rf=RandomForestClassifier(n_estimators =20)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9730639730639731

In [15]:
def get_score(model):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [16]:
get_score(lr)

0.9730639730639731

In [17]:
from sklearn.model_selection import KFold

In [19]:
l=[1,2,3,4,5,6,7,8,9]

In [18]:
fold = KFold(n_splits = 4)

In [20]:
for train_index ,test_index in fold.split(l):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [21]:
from sklearn.model_selection import StratifiedKFold

In [22]:
fold = StratifiedKFold(n_splits=4)

In [23]:
lr_score = []
svm_score = []
rf_score = []

In [24]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [25]:
for train_index , test_index in fold.split(digits.data,digits.target):
    X_train, X_test = digits.data[train_index],digits.data[test_index]
    y_train, y_test = digits.target[train_index],digits.target[test_index]
    lr_score.append(get_score(lr,X_train,X_test,y_train, y_test))
    svm_score.append(get_score(svm,X_train,X_test,y_train, y_test))
    rf_score.append(get_score(rf,X_train,X_test,y_train, y_test))

In [26]:
lr_score

[0.9355555555555556, 0.9131403118040089, 0.955456570155902, 0.9175946547884187]

In [27]:
svm_score

[0.9622222222222222,
 0.9665924276169265,
 0.9821826280623608,
 0.9510022271714922]

In [28]:
rf_score

[0.94, 0.8819599109131403, 0.9665924276169265, 0.9198218262806236]

In [29]:
from sklearn.model_selection import cross_val_score

In [31]:
cross_val_score(LogisticRegression(max_iter =7400),digits.data,digits.target,cv=4)

array([0.93555556, 0.91314031, 0.95545657, 0.91759465])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators = 5),digits.data,digits.target,cv=4)

array([0.87333333, 0.83518931, 0.86859688, 0.82405345])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators = 15),digits.data,digits.target,cv=4)

array([0.92      , 0.90423163, 0.93986637, 0.92650334])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators = 25),digits.data,digits.target,cv=4)

array([0.94222222, 0.90423163, 0.95545657, 0.922049  ])