importing libraries

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [42]:
df = pd.read_csv('C:\\Users\\LENOVO\\House_prediction1.csv')

In [43]:
df.shape

(40, 3)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   town    39 non-null     object
 1   area    40 non-null     int64 
 2   price   40 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 1.1+ KB


In [45]:
df.head()

town  area    price
0  Mumbai  2000  5500000
1  Mumbai  2100  5530000
2  Mumbai  2200  5560000
3  Mumbai  2300  5590000
4  Mumbai  2400  5620000

In [46]:
df['town'].unique()

array(['Mumbai', 'Pune', 'Delhi', nan], dtype=object)

label encoding

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
label_encoder = LabelEncoder()

In [49]:
df['town'] = label_encoder.fit_transform(df['town'])

In [50]:
df.head()

town  area    price
0     1  2000  5500000
1     1  2100  5530000
2     1  2200  5560000
3     1  2300  5590000
4     1  2400  5620000

In [51]:
df

town  area    price
0      1  2000  5500000
1      1  2100  5530000
2      1  2200  5560000
3      1  2300  5590000
4      1  2400  5620000
5      2  2500  5650000
6      2  2600  5680000
7      2  2700  5710000
8      2  2800  5740000
9      0  2900  5770000
10     0  3000  5800000
11     0  3100  5830000
12     0  3200  5860000
13     1  3300  5890000
14     1  3400  5920000
15     1  3500  5950000
16     1  3600  5980000
17     1  3700  6010000
18     2  3800  6040000
19     2  3900  6070000
20     2  4000  6100000
21     2  4100  6130000
22     0  4200  6160000
23     0  4300  6190000
24     0  4400  6220000
25     0  4500  6250000
26     1  4600  6280000
27     1  4700  6310000
28     1  4800  6340000
29     1  4900  6370000
30     1  5000  6400000
31     2  5100  6430000
32     2  5200  6460000
33     2  5300  6490000
34     2  5400  6520000
35     0  5500  6550000
36     0  5600  6580000
37     0  5700  6610000
38     0  5800  6640000
39     3  5900  6670000

In [52]:
df.sample(5)

town  area    price
0      1  2000  5500000
32     2  5200  6460000
22     0  4200  6160000
33     2  5300  6490000
26     1  4600  6280000

In [53]:
X = df.drop(['price'],axis=1)
y = df.price

In [54]:
X.head()

town  area
0     1  2000
1     1  2100
2     1  2200
3     1  2300
4     1  2400

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [56]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [57]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [58]:
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [59]:
y_pred = model.predict(X_test)

pickle and joblin

In [60]:
import pickle

In [61]:
with open ('model_pickle','wb') as f:
    pickle.dump(model,f)

In [62]:
with open ('model_pickle','rb') as f :
    prediction=pickle.load(f)

In [63]:
X_test

town  area
19     2  3900
16     1  3600
15     1  3500
26     1  4600
4      1  2400
12     0  3200
37     0  5700
27     1  4700
39     3  5900
6      2  2600
25     0  4500
9      0  2900
13     1  3300
31     2  5100

In [64]:
prediction.predict(X_test)

array([6070000., 5980000., 5950000., 6280000., 5620000., 5860000.,
       6610000., 6310000., 6670000., 5680000., 6250000., 5770000.,
       5890000., 6430000.])

In [65]:
prediction.predict([[1,2700]])

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5710000.])

get dummies

In [66]:
df = pd.read_csv('C:\\Users\\LENOVO\\House_prediction1.csv')

In [67]:
df.head()

town  area    price
0  Mumbai  2000  5500000
1  Mumbai  2100  5530000
2  Mumbai  2200  5560000
3  Mumbai  2300  5590000
4  Mumbai  2400  5620000

In [68]:
df.town.unique()

array(['Mumbai', 'Pune', 'Delhi', nan], dtype=object)

In [69]:
dummies = df.town
dummies.head(3)

0    Mumbai
1    Mumbai
2    Mumbai
Name: town, dtype: object

In [70]:
dummies = pd.get_dummies(dummies)

In [71]:
dummies

Delhi  Mumbai  Pune
0       0       1     0
1       0       1     0
2       0       1     0
3       0       1     0
4       0       1     0
5       0       0     1
6       0       0     1
7       0       0     1
8       0       0     1
9       1       0     0
10      1       0     0
11      1       0     0
12      1       0     0
13      0       1     0
14      0       1     0
15      0       1     0
16      0       1     0
17      0       1     0
18      0       0     1
19      0       0     1
20      0       0     1
21      0       0     1
22      1       0     0
23      1       0     0
24      1       0     0
25      1       0     0
26      0       1     0
27      0       1     0
28      0       1     0
29      0       1     0
30      0       1     0
31      0       0     1
32      0       0     1
33      0       0     1
34      0       0     1
35      1       0     0
36      1       0     0
37      1       0     0
38      1       0     0
39      0       0     0

In [72]:
final_df =pd.concat([df,dummies],axis=1)

In [73]:
final_df.head()

town  area    price  Delhi  Mumbai  Pune
0  Mumbai  2000  5500000      0       1     0
1  Mumbai  2100  5530000      0       1     0
2  Mumbai  2200  5560000      0       1     0
3  Mumbai  2300  5590000      0       1     0
4  Mumbai  2400  5620000      0       1     0

In [74]:
final_df.drop(['Pune','town'],axis=1,inplace = True)

In [75]:
final_df.head(3)

area    price  Delhi  Mumbai
0  2000  5500000      0       1
1  2100  5530000      0       1
2  2200  5560000      0       1

In [84]:
X = final_df.drop(['price'],axis=1)
y = final_df.price

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [86]:
from joblib import dump ,load 


In [87]:
dump(model,'joblib_model')

['joblib_model']

In [88]:
y_predict =model.predict(X_test)

In [90]:
model.predict([[2200,0,1]])

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5560000.])