importing libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
import tensorflow as tf
from tensorflow import keras

Forward Propagation

In [ ]:
X=np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
W=np.array([[0,0,0],[-0.5,0,1],[-0.5,1,0],[-0.5,1,1]])

In [ ]:

Z=np.sum(X*W,axis=1)
Z

array([0. , 0.5, 0.5, 1.5])

In [ ]:
Z=Z.reshape(Z.shape[0],1)
Z

array([[0. ],
       [0.5],
       [0.5],
       [1.5]])

In [ ]:
model = keras.activations.sigmoid(Z)
model

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.5       ],
       [0.62245933],
       [0.62245933],
       [0.81757448]])>

In [ ]:
def sigmoid(Z):
  e=1/(1+np.exp(-(Z)))
  return e

In [ ]:
e=sigmoid(Z)
e

array([[0.5       ],
       [0.62245933],
       [0.62245933],
       [0.81757448]])

In [ ]:
p=np.array(model)
p

array([[0.5       ],
       [0.62245933],
       [0.62245933],
       [0.81757448]])

In [ ]:
def threshold(p):
  total=[]
  for i in p:
    if i >= 0.5:
      q=1
      total.append(q)
    else :
      q=0
      total.append(q)
  s= np.array(total)
  return s

In [ ]:
t=threshold(p)
t=t.reshape(t.shape[0],1)
t

array([[1],
       [1],
       [1],
       [1]])

In [ ]:
y=np.array([[0],[1],[1],[1]])
y

array([[0],
       [1],
       [1],
       [1]])

In [ ]:
def loss(y,p_cap):
  x=-y*np.log(p_cap)-(1-y)*np.log(1-p_cap)
  return x

In [ ]:
x=loss(y,p)
x

array([[0.69314718],
       [0.47407698],
       [0.47407698],
       [0.20141328]])

backward propagation

In [ ]:
def L_p(y,p_cap):
  c=(-y/p_cap)+(1-y)/(1-p_cap)
  return c


In [ ]:
c=L_p(y,p)
c

array([[ 2.        ],
       [-1.60653066],
       [-1.60653066],
       [-1.22313016]])

In [ ]:
def p_z(p_cap):
  d=p_cap*(1-p_cap)
  return d


In [ ]:
d=p_z(p)
d

array([[0.25      ],
       [0.23500371],
       [0.23500371],
       [0.14914645]])

In [ ]:
L_z=c*d
L_z

array([[ 0.5       ],
       [-0.37754067],
       [-0.37754067],
       [-0.18242552]])

In [ ]:
error=L_z*X

In [ ]:
alpha=1
W1=W-alpha*error

In [ ]:
W1

array([[-0.5       ,  0.        ,  0.        ],
       [-0.12245933,  0.        ,  1.37754067],
       [-0.12245933,  1.37754067,  0.        ],
       [-0.31757448,  1.18242552,  1.18242552]])

In [ ]:
Z=np.sum(X*W1,axis=1)
Z

array([-0.5       ,  1.25508134,  1.25508134,  2.04727657])

In [ ]:
Z=Z.reshape(Z.shape[0],1)
Z

array([[-0.5       ],
       [ 1.25508134],
       [ 1.25508134],
       [ 2.04727657]])

In [ ]:
model1=keras.activations.sigmoid(Z)
p1=np.array(model1)
p1

array([[0.37754067],
       [0.77817823],
       [0.77817823],
       [0.88567214]])

In [ ]:
t=threshold(p1)
t=t.reshape(t.shape[0],1)
t

array([[0],
       [1],
       [1],
       [1]])

In [ ]:
class programming_assignment_4_Module1:
  X=np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
  W=np.array([[0,0,0],[-0.5,0,1],[-0.5,1,0],[-0.5,1,1]])
  y=np.array([[0],[1],[1],[1]])
  print('Y_train=',y)
  def threshold(p):
    total=[]
    for i in p:
      if i >= 0.5:
        q=1
        total.append(q)
      else :
        q=0
        total.append(q)
    s= np.array(total)
    return s
  def loss(y,p_cap):
    x=-y*np.log(p_cap)-(1-y)*np.log(1-p_cap)
    return x
  def p_z(p_cap):
    d=p_cap*(1-p_cap)
    return d
  def Forward_Propagation(self,X,W,y):
    Z=np.sum(X*W,axis=1)
    Z=Z.reshape(Z.shape[0],1)
    model = keras.activations.sigmoid(Z)
    global p
    p=np.array(model)
    t=threshold(p)
    t=t.reshape(t.shape[0],1)
    print('Y_predicted =',t)
    x=loss(y,p)
    print('errors in each y_predicted =',x)
  def Back_Propagation(self,y,X,W,p):
    c=L_p(y,p)
    d=p_z(p)
    error=L_z*X
    alpha=1
    W=W-alpha*error
    print('weights for x train=',W)
    Z=np.sum(X*W,axis=1)
    Z=Z.reshape(Z.shape[0],1)
    model1=keras.activations.sigmoid(Z)
    p1=np.array(model1)
    t=threshold(p1)
    t=t.reshape(t.shape[0],1)
    print('correctly predicted y')

Y_train= [[0]
 [1]
 [1]
 [1]]


In [ ]:
c=programming_assignment_4_Module1()

In [ ]:
c.Forward_Propagation(X,W,y)

Y_predicted = [[1]
 [1]
 [1]
 [1]]
errors in each y_predicted = [[0.69314718]
 [0.47407698]
 [0.47407698]
 [0.20141328]]


In [ ]:
c.Back_Propagation(y,X,W,p)

weights for x train= [[-0.5         0.          0.        ]
 [-0.12245933  0.          1.37754067]
 [-0.12245933  1.37754067  0.        ]
 [-0.31757448  1.18242552  1.18242552]]
correctly predicted y
