importing library

In [ ]:
import numpy as np 

Detailed work

In [ ]:
A=np.array([[-1,1,0,0,0,0,0,1],[0,-1,1,-1,0,0,0,0],[0,0,0,0,0,-1,1,-1],[0,0,0,1,-1,1,0,0]])
A

array([[-1,  1,  0,  0,  0,  0,  0,  1],
       [ 0, -1,  1, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  1, -1],
       [ 0,  0,  0,  1, -1,  1,  0,  0]])

In [ ]:
rank_A=np.linalg.matrix_rank(A)
rank_A

4

In [ ]:
b=np.array([[50],[60],[30],[40]])

In [ ]:
b

array([[50],
       [60],
       [30],
       [40]])

In [ ]:
multiplication=np.dot(A,A.T)
multiplication

array([[ 3, -1, -1,  0],
       [-1,  3,  0, -1],
       [-1,  0,  3, -1],
       [ 0, -1, -1,  3]])

In [ ]:
P=np.linalg.inv(multiplication)
P

array([[0.46666667, 0.2       , 0.2       , 0.13333333],
       [0.2       , 0.46666667, 0.13333333, 0.2       ],
       [0.2       , 0.13333333, 0.46666667, 0.2       ],
       [0.13333333, 0.2       , 0.2       , 0.46666667]])

In [ ]:
X=np.dot(A.T,P)
X

array([[-0.46666667, -0.2       , -0.2       , -0.13333333],
       [ 0.26666667, -0.26666667,  0.06666667, -0.06666667],
       [ 0.2       ,  0.46666667,  0.13333333,  0.2       ],
       [-0.06666667, -0.26666667,  0.06666667,  0.26666667],
       [-0.13333333, -0.2       , -0.2       , -0.46666667],
       [-0.06666667,  0.06666667, -0.26666667,  0.26666667],
       [ 0.2       ,  0.13333333,  0.46666667,  0.2       ],
       [ 0.26666667,  0.06666667, -0.26666667, -0.06666667]])

In [ ]:
x=np.dot(X,b)
x

array([[-46.66666667],
       [ -3.33333333],
       [ 50.        ],
       [ -6.66666667],
       [-43.33333333],
       [  3.33333333],
       [ 40.        ],
       [  6.66666667]])

In [ ]:
vec_norm = np.linalg.norm(x)
vec_norm

90.92121131323904

In [ ]:
Q=np.hstack((A,b))
Q

array([[-1,  1,  0,  0,  0,  0,  0,  1, 50],
       [ 0, -1,  1, -1,  0,  0,  0,  0, 60],
       [ 0,  0,  0,  0,  0, -1,  1, -1, 30],
       [ 0,  0,  0,  1, -1,  1,  0,  0, 40]])

In [ ]:
rank_Q=np.linalg.matrix_rank(Q)
rank_Q

4

In [ ]:
rank_nullity = A.shape[1]-rank_A
rank_nullity

4

Concise work into class

In [ ]:
class programmimg_assignment_2 :
  A=np.array([[-1,1,0,0,0,0,0,1],[0,-1,1,-1,0,0,0,0],[0,0,0,0,0,-1,1,-1],[0,0,0,1,-1,1,0,0]])
  b=np.array([[50],[60],[30],[40]])
  
  def unknown_variable(self,A,b):
    multiplication=np.dot(A,A.T)
    P=np.linalg.inv(multiplication)
    X=np.dot(A.T,P)
    x=np.dot(X,b)
    print('The solution point is =',x)
    print('The norm of unknown variable is ',np.linalg.norm(x))
  def rank_A(self,A):
    print('the rank of A is',np.linalg.matrix_rank(A))
  def rank_Ab(self,A,b):
    Q=np.hstack((A,b))
    print('The rank of A given b is ',np.linalg.matrix_rank(Q))
  def rank_nullity(self,A):
    print('Rank-Nullity of matrix A is',A.shape[1]-np.linalg.matrix_rank(A))
    

In [ ]:
c=programmimg_assignment_2()
c.unknown_variable(A,b)

The solution point is = [[-46.66666667]
 [ -3.33333333]
 [ 50.        ]
 [ -6.66666667]
 [-43.33333333]
 [  3.33333333]
 [ 40.        ]
 [  6.66666667]]
The norm of unknown variable is  90.92121131323904


In [ ]:
c.rank_A(A)

the rank of A is 4


In [ ]:
c.rank_Ab(A,b)

The rank of A given b is  4


In [ ]:
c.rank_nullity(A)

Rank-Nullity of matrix A is 4
